### ISSUE TITLE
Literally can't open

### ISSUE THREAD

**Issue by TheAwesomeZave** [basiccube/GodotTower#7]
Whenever I open the project, it freezes up, and I have to use Task Manager to close it.
It gave an error the first time regarding BitmapTextureFont, but it's still doing this after adding the latest version of the plugin.

I'm using Godot 3.5.3 stable.

**Comment by basiccube** [comment]
Can you provide a screenshot or video of the moment when Godot freezes?

**Comment by TheAwesomeZave** [comment]
Nevemind, it just takes REALLY long to load. Sorry!
