### ISSUE TITLE
I can't launch the project(Godot 3.5.3)

### ISSUE THREAD

**Issue by AndriiParf** [basiccube/GodotTower#8]
![Godot_v3 5 3-stable_win64_oj4LWH3ljs](https://github.com/basiccube/GodotTower/assets/79785557/87343250-4336-46fd-a030-816df2abbe32)

**Comment by basiccube** [comment]
Just ignore that error. Have you tried waiting a few minutes for the project to load?

**Comment by AndriiParf** [comment]
Project just hangs if I ignore the error

**Comment by basiccube** [comment]
That's where you have to wait for it to load.

**Comment by AndriiParf** [comment]
Sorry, the project took 10-15 minutes to load. We're sorry!
